# Generated by Django 5.1 on 2024-08-15 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Content',
            new_name='content',
        ),
    ]
